config/routes.rb
Rails.application.routes.draw do
  get 'test/move'

  resources :commands

  resources :users do
    get 'active_game/index'

    resources :games do
      resources :instructions

      get 'active_game/activate'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :statistics

  root 'statistics#index'
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  # id, integer, PKEY, NOT NULL
  # game_id, integer, foreign_key, NOT NULL
  # command_id, integer, foreign_key, NOT NULL
  # parameters, text (serialized as JSON/Ruby Hash), NULL
  # precedence, integer, NOT NULL, default: 0

  belongs_to :game
  belongs_to :command

  serialize :parameters
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  before_action :set_user
  before_action :set_game
  before_action :set_instruction, only: [:show, :edit, :update, :destroy]

  # GET /instructions
  # GET /instructions.json
  def index
    @instructions = @game.instructions.all

    respond_to do |format|
      format.html { render action: :index }
      format.json do
        render json: { instructions: @instructions.map { |i| i.command.data } }
      end
    end
  end

  # GET /instructions/1
  # GET /instructions/1.json
  def show
  end

  # GET /instructions/new
  def new
    @instruction = @game.instructions.build
  end

  # GET /instructions/1/edit
  def edit
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @instruction = Instruction.new(instruction_params)

    respond_to do |format|
      if @instruction.save
        format.html { redirect_to [@user, @game, @instruction], notice: 'Instruction was successfully created.' }
        format.json { render :show, status: :created, location: @instruction }
      else
        format.html { render :new }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructions/1
  # PATCH/PUT /instructions/1.json
  def update
    respond_to do |format|
      if @instruction.update(instruction_params)
        format.html { redirect_to [@user, @game, @instruction], notice: 'Instruction was successfully updated.' }
        format.json { render :show, status: :ok, location: @instruction }
      else
        format.html { render :edit }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    @instruction.destroy
    respond_to do |format|
      format.html { redirect_to user_game_instructions_url(@user, @game), notice: 'Instruction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_game
    @game = Game.find(params[:game_id])
  end

  def set_instruction
    @instruction = @game.instructions.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def instruction_params
    params
      .require(:instruction)
      .permit(:game_id, :command_id, :name, :parameters, :precedence)
  end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/instructions/_form.html.slim
= form_for [@user, @game, @instruction] do |f|
  - if @instruction.errors.any?
    #error_explanation
      h2 = "#{pluralize(@instruction.errors.count, "error")} prohibited this instruction from being saved:"
      ul
        - @instruction.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :game_id
    = f.text_field :game_id
  .field
    = f.label :command_id
    - commands = Command.all.map { |c| [c.name, c.id] }
    = f.select :command_id, commands
  .field
    = f.label :precedence
    = f.text_field :precedence
  .actions = f.submit

app/views/instructions/_index.html.slim
/Locals:
/instructions

h1 Listing instructions

table
  thead
    tr
      th Game
      th Precedence
      th Command
      th
      th
      th

  tbody
    - instructions.order(:precedence).each do |instruction|
      tr
        td = instruction.game.name
        td = instruction.precedence
        td = instruction.command.name
        td = link_to 'Show', [@user, @game, instruction]
        td = link_to 'Edit', edit_user_game_instruction_path(@user, @game, instruction)
        td = link_to 'Destroy', [@user, @game, instruction], data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Instruction', new_user_game_instruction_path(@user, @game)

app/views/instructions/edit.html.slim
h1 Editing instruction

== render 'form'

= link_to 'Show', [@user, @game, @instruction]
'&nbsp;|
= link_to 'Back', user_game_instructions_path(@user, @game)

app/views/instructions/index.html.slim
== render partial: 'index', locals: { instructions: @instructions }

app/views/instructions/new.html.slim
h1 New instruction

== render 'form'

= link_to 'Back', user_game_instructions_path(@user, @game)

app/views/instructions/show.html.slim
p#notice = notice

p
  strong Game:&nbsp;
  = @instruction.game.name
p
  strong Command:&nbsp;
  = @instruction.command.name
p
  strong Data:&nbsp;
  = @instruction.command.data
p
  strong Precedence:&nbsp;
  = @instruction.precedence

= link_to 'Edit', edit_user_game_instruction_path(@user, @game, @instruction)
'&nbsp;|
= link_to 'Back', user_game_instructions_path(@user, @game)