config/routes.rb
Rails.application.routes.draw do
  get 'test/move'

  resources :commands

  resources :users do
    get 'active_game/index'

    resources :games do
      resources :instructions

      get 'active_game/activate'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :statistics

  root 'statistics#index'
end

app/models/command.rb
class Command < ActiveRecord::Base
  # id, integer, PKEY, NOT NULL
  # name, string, unique index, NOT NULL
  # data, integer, NOT NULL

  has_many :instructions
  has_many :games, through: :instructions

  has_many :instructions
  has_many :games, through: :instructions

  validates :name, presence: true, uniqueness: true
  validates :data, presence: true
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]

  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(command_params)

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render :show, status: :created, location: @command }
      else
        format.html { render :new }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { render :show, status: :ok, location: @command }
      else
        format.html { render :edit }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url, notice: 'Command was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_command
    @command = Command.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def command_params
    params.require(:command).permit(:name, :data)
  end
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.slim
= form_for @command do |f|
  - if @command.errors.any?
    #error_explanation
      h2 = "#{pluralize(@command.errors.count, "error")} prohibited this command from being saved:"
      ul
        - @command.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :data
    = f.text_field :data
  .actions = f.submit

app/views/commands/edit.html.slim
h1 Editing command

== render 'form'

= link_to 'Show', @command
'|
= link_to 'Back', commands_path

app/views/commands/index.html.slim
h1 Listing commands

table
  thead
    tr
      th Name
      th Data
      th
      th
      th

  tbody
    - @commands.each do |command|
      tr
        td = command.name
        td = command.data
        td = link_to 'Show', command
        td = link_to 'Edit', edit_command_path(command)
        td = link_to 'Destroy', command, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Command', new_command_path

app/views/commands/new.html.slim
h1 New command

== render 'form'

= link_to 'Back', commands_path

app/views/commands/show.html.slim
p#notice = notice

p
  strong Name:
  = @command.name
p
  strong Data:
  = @command.data

= link_to 'Edit', edit_command_path(@command)
'|
= link_to 'Back', commands_path